language: node_js
node_js:
  - "6"
  - "7"
  - "node"
sudo: false
# download test suite and run tests... submodule? meta testing project with
# all of the reference implementations?
script:
  - npm run test-all
notifications:
  email:
    on_success: change
    on_failure: change
